---
title: "NOAA Biosampling Species Summaries"
output: 
  flexdashboard::flex_dashboard:
    source_code: "https://github.com/evaschemmel-NOAA-LHP"
    orientation: rows
    vertical_layout: fill
    theme:
      version: 4
      bg: "#FFFFFF"
      fg: "#000000" 
      primary: "#005AA8"
      
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(lubridate)
library(magrittr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(gridExtra)

# Install thematic and un-comment for themed static plots (i.e., ggplot2)
# thematic::thematic_rmd()
```

```{r}
here::i_am("biosampling.Rmd")
source(here::here("functions", "dataplot_simple.R"))

```

```{r global, include=FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

data <- read.csv("data/all_samples.csv")

#set up species and region lists for dropdown menu
region_list <- c("A.Samoa", "A.Samoa_unfished", "Guam", "CNMI", "CNMI_unfished")
species_list <- na.omit((unique(data$ScientificName)))

```


```{r}

#region_list<-selectInput("Region", label = "Region:",
#            choices = c("A.Samoa", "A.Samoa_unfished", "Guam", "CNMI", "CNMI_unfished"), selected = "Guam")


#species_list<-selectInput("ScientificName", label = "Species",
#            choices = unique(data$ScientificName), selected = "Aphareus rutilans")

# selectedData <- reactive({
#  data <- data |> filter(Region == input$Region & ScientificName==input$ScientificName)
# })

#selectedData <- reactive({
#  data[, c(input$Region, input$ScientificName, "Length.cm.", "Sex", "Date", "GonWeight", "Weight.g." )]
#})

```


# Sidebar {.sidebar}

<span style="color:#005AA8">

<h4>**Choose a region and species** to begin:</h4>

</span>

```{r}
# Select indicator to view - start with SST selected
div(style = "margin-top: -20px; ", #decreases amount of whitespace between label and input selection UI
  selectInput('Region', label = ' ', choices = region_list, selected = c('Guam'))
)

div(style = "margin-top: -20px; ", #decreases amount of whitespace between label and input selection UI
  selectInput('Species', label = ' ', choices = species_list, selected = c('Aphareus rutilans'))
)

```

Species Summary
======================================================================

Row
-----------------------------------------------------------------------

```{r}

output$text_summary <- renderUI({
  
  # Filter data
  temp <- data |> filter(Region == input$Region, ScientificName == input$Species)
  
  temp$Month<-month(temp$Date, label=TRUE) #keeps month data in date formatt for plotting in order
  tempm<-temp%>% 
    na.omit(temp)
  Months<-c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "July", "Aug", "Sep", "Oct", "Nov", "Dec")
  Mn=c(1:10, 1)
  Months<-as.data.frame(Months)
  Months<-as.factor(Months$Months)
  tempm<-tempm %>%
    dplyr::group_by(Month)%>%
    dplyr::summarize(N_month=length(Length.cm.))
  maxm<-max(tempm$N_month, na.rm=TRUE)
  maxm<-if (maxm >=20) maxm else 20
  tempm<-tidyr::complete(tempm, Month, fill=list(N_Month=0))
  gsi<-temp %>% 
    dplyr::mutate(GSI=(GonWeight/Weight.g.)*100)
  
  #join into list
  build_list<-list(temp, tempm, gsi)
  names(build_list)<- c('temp','tempm','gsi')
  final_list<-build_list
  sample_size=length(final_list$temp$Length.cm.)
  length_min<-min(final_list$temp$Length.cm., na.rm=TRUE)
  length_max<-max(final_list$temp$Length.cm., na.rm=TRUE)
  length_median<-median(final_list$temp$Length.cm., na.rm=TRUE)
  gender<-final_list$temp %>%
    dplyr::group_by(Sex)%>%
    dplyr::summarize(n_females=length(Sex=="F"))
  female=gender[1,2]
  male=gender[2,2]
  unknown=gender[3,2]
  
  maxm<-max(final_list$tempm$N_month, na.rm=TRUE)
  maxm<-if (maxm >=20) maxm else 20
  
  #unpretty formatting but I could not get inline variables (line below) to work
  paste0("A total of ", sample_size, " samples (females=", female, ", males=", male,
         ", unknown/na=", unknown, ") have been collected to date. Median fork length is ",
         length_median, " cm (min=", length_min, "cm, max=", length_max, " cm).")
  
  #markdown("A total of `r sample_size` samples (females=`r female`, males=`r male`, unknown/na=`r unknown`) have been collected to date. Median fork length is `r median` cm (min=`r min` cm, max=`r max` cm).")
  
})

uiOutput("text_summary")

```

Row
-----------------------------------------------------------------------

```{r}

output$four_panel_plot <- renderPlot({

  # Filter data
  temp <- data |> filter(Region == input$Region, ScientificName == input$Species)
  
  temp$Month<-month(temp$Date, label=TRUE) #keeps month data in date formatt for plotting in order
  tempm<-temp%>% 
    na.omit(temp)
  Months<-c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "July", "Aug", "Sep", "Oct", "Nov", "Dec")
  Mn=c(1:10, 1)
  Months<-as.data.frame(Months)
  Months<-as.factor(Months$Months)
  tempm<-tempm %>%
    group_by(Month)%>%
    dplyr::summarize(N_month=length(Length.cm.))
  maxm<-max(tempm$N_month, na.rm=TRUE)
  maxm<-if (maxm >=20) maxm else 20
  tempm<-complete(tempm, Month, fill=list(N_Month=0))
  gsi<-temp %>% 
    mutate(GSI=(GonWeight/Weight.g.)*100)
  
  #join into list
  build_list<-list(temp, tempm, gsi)
  names(build_list)<- c('temp','tempm','gsi')
  final_list<-build_list
  length_min<-min(final_list$temp$Length.cm., na.rm=TRUE)
  length_max<-max(final_list$temp$Length.cm., na.rm=TRUE)
  
    bin_width=2
    nbins <- seq(length_min - bin_width,
                 length_max + bin_width,
                 by = bin_width)
    p1 <- ggplot(data=temp, aes(x=Length.cm.))+geom_histogram(binwidth=2,breaks=nbins, color="black", aes(fill=Sex)) + 
      xlab("Fork Length (cm)") +  ylab("Frequency") + ggtitle("Size Distribution")+
      scale_fill_manual(values=c("red", "blue", "white", "black"))+
      theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                         panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), legend.position="none")+scale_x_continuous(limits = c(length_min-2, length_max+2))
    
    
    #monthly samples
    p2<-ggplot(tempm, aes(x=Month, y=tempm$N_month)) + 
      geom_bar(stat = "identity")+xlab("") +  ylab("Frequency") + ggtitle("Monthly Sample Distribution")+
      geom_hline(yintercept = 20, colour="red", linetype = "dashed")+ theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                                                                                         panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), legend.position="none")
    
    #GSI
    p3<-ggplot(gsi, aes(x=Length.cm., y=GSI, color=Sex)) +  xlab("Fork Length (cm)") +  ylab("GSI") + ggtitle("GSI & Fish Length")+
      geom_point(aes(colour=Sex), size=2) +
      geom_point(shape = 1,size=2, colour = "black") + scale_color_manual(values=c("red", "blue", "white", "black"))+
      theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                         panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), legend.position="none")
    
    
    #Spawning Season
    gsi_f<-gsi %>% 
      subset(Sex=="F")
    gsi_f$Month<-month(gsi_f$Date, label=TRUE)
    
    p4<-ggplot(gsi_f, aes(x=as.factor( Month), y=GSI)) + 
      geom_boxplot(fill="red") +
      xlab("") +  ylab("GSI") + ggtitle("Spawning Season")+
      theme_bw() + theme(panel.border = element_blank(), panel.grid.major = element_blank(),
                         panel.grid.minor = element_blank(), axis.line = element_line(colour = "black"), legend.position="none")+scale_x_discrete(limits = month.abb)
    
    grid.arrange(p1,p2,p3,p4 , nrow = 2)
}
)

plotOutput("four_panel_plot")

```